CONTIKI_PROJECT = tans_native
all: $(CONTIKI_PROJECT)

CONTIKI = /home/andezion/contiki-ng

PROJECT_SOURCEFILES += tans_embedded.c

PROJECT_CONF_PATH = ./project-conf.h

TARGET ?= native

include $(CONTIKI)/Makefile.include
