#ifndef WORK1_PROJECT_CONF_H
#define WORK1_PROJECT_CONF_H

#define UIP_CONF_IPV6 1
#define UIP_CONF_BUFFER_SIZE 1280
#define QUEUEBUF_CONF_NUM 16
#define UIP_CONF_MAX_ROUTES 30
#define NBR_TABLE_CONF_MAX_NEIGHBORS 10
#define UIP_CONF_DS6_REACHABLE_TIME 600000UL
#define LOG_LEVEL_APP LOG_LEVEL_INFO
#define LOG_LEVEL_NET LOG_LEVEL_INFO
#define UIP_CONF_TCP 0
#define UIP_CONF_UDP 1
#define UIP_CONF_UDP_CHECKSUMS 1
#define PROCESS_CONF_FASTPOLL_DISABLE 0

#endif //WORK1_PROJECT_CONF_H